!!python/object:argparse.Namespace
Vh_gnn_layers: 1
Vl_gnn_layers: 2
actor_gnn_layers: 2
algo: dgppo
alpha: 10.0
batch_size: 16384
cbf_eps: 0.01
cbf_weight: 1.0
clip_eps: 0.25
coef_ent: 0.01
cost_schedule: false
cost_weight: 0.0
debug: false
env: LidarDubinsCircle
eval_epi: 1
eval_interval: 50
full_observation: false
lagr_init: 0.5
log_dir: ./logs
lr_Vh: 0.0003
lr_Vl: 0.0003
lr_actor: 1.0e-05
lr_lagr: 1.0e-07
n_env_test: 32
n_env_train: 128
n_rays: 32
name: null
no_cbf_schedule: false
no_rnn: true
num_agents: 1
obs: 0
rnn_layers: 1
rnn_step: 16
save_interval: 50
seed: 0
steps: 200000
use_lstm: false
Vh_gnn_layers: 1
Vl_gnn_layers: 2
actor_gnn_layers: 2
alpha: 10.0
batch_size: 16384
cbf_eps: 0.01
cbf_schedule: true
cbf_weight: 1.0
clip_eps: 0.25
coef_ent: 0.01
cost_schedule: false
cost_weight: 0.0
epoch_ppo: 1
gae_lambda: 0.95
gamma: 0.99
lagr_init: 0.78
lr_Vh: 0.0003
lr_Vl: 0.0003
lr_actor: 1.0e-05
lr_lagr: 1.0e-07
max_grad_norm: 2.0
rnn_layers: 1
rnn_step: 16
seed: 0
use_lstm: false
use_rnn: false
